version: 2
jobs:
  build:
    docker:
    - image: node:latest
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
        - node-deps-v1-{{ .Branch }}
        - node-deps-v1
    - run:
        name: install, build, test
        command: |
          node -v
          npm -v
          yarn install
          yarn all
          yarn test
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/repo/node_modules
workflows:
  version: 2
  build:
    jobs:
    - build
