
version: 2.1
orbs:
  codecov: codecov/codecov@5.3.0

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  main-task:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:23.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: yarn install
          command: |
            yarn install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint, build, test
          command: |
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            echo '               lint -> build -> test'
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            echo "node: $(node -v)"
            echo "npm : $(npm -v)"
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            echo '                  run lint, build'
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            npm run all
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            echo '                     run test'
            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
            npm run test
    
      - codecov/upload
          # file: "./coverage/coverage-final.json"

workflows:
  build:
    jobs:
      - main-task
