version: 2.1
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/node
  node: circleci/node@1.1.6 # refers to the Orbs of circleci/node as `node`
jobs:
  build:
    executor:
      name: node/default
      tag: "latest"
    working_directory: ~/repo

    steps:
      - checkout
      - node/with-cache:
          dir: ~/repo/node_modules
          cache-version: v1
          steps:
          - run:
              name: install, build, test
              command: |
                node -v
                npm -v
                yarn install
                yarn all
                yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
